### PR TITLE
[DAWN] Update deps, make lint fixes

### PR DESCRIPTION
**Pull request by kevinji**
Most exciting is Webpack 3.0.0!

### CODE REVIEW

**Comment by kevinji** [comment]
<s>Note: this is blocked on airbnb/javascript#1447.</s>

EDIT: The above issue has been resolved.

**Comment by kevinmasd** [comment]
Everything ready? Build still works?

**Comment by kevinji** [comment]
Everything looks okay, but feel free to take a look.

**Review by kevinmasd — APPROVED** [review]
Can confirm that it works.

**Pull request merged**
