### PR TITLE
[HIBIKE] runtime integration fixes

### PR DESCRIPTION
**Pull request by karthik-shanmugam**
- update `hibike_process.py` to send uid's along with device values, as was written in the integration spec (fix implementation to match documentation)
- update and rename integration spec
  - add `[]`'s around arguments to accurately reflect how contents of messages are nested (fix documentation to match implementation)
  - rename ATALANTA => RUNTIME

### CODE REVIEW

**Review by yizow — DISMISSED** [review]
LGTM. 

Does the implementation change break anything? Cause i don't see the 'receiving end' changes

**Review by yizow — COMMENTED** [review]
Mostly LGTM, but does the implementation change break anything? Cause i don't see the 'receiving end' changes

**Comment by karthik-shanmugam** [comment]
@yizow  The only "receiving end" within hibike was just printing out the whole message to console anyways. If runtime did any integration around this it would almost definitely break that though.

**Review by yizow — APPROVED** [review]
`device_values` command is not actually implemented on runtime side. Adding to my todo

**Pull request merged**
