### PR TITLE
Integration/chris

### PR DESCRIPTION
**Pull request by Alramech**
Unifies dawn and runtime robot states.
Not sure if this properly exposes the enums to dawn

### CODE REVIEW

**Comment by yizow** [comment]
@bodiddles you or brandon should handle updating the runtime side as well.

**Comment by kevinmasd** [comment]
Will probably conflict with #199 . Also build failure.

**Comment by brandonxxlee** [comment]
@bodiddles Proabably needs to rebuild protos
Will update runtime changes, should probably double check all appropriate enum uses are updated.

**Comment by kevinji** [comment]
Don't worry about merge conflicts with my PR; I can handle those after this gets merged in.

**Comment by brandonxxlee** [comment]
I am pretty sure I have updated all instances in runtime.

**Comment by nikitakit** [comment]
FYI the Makefile in the runtime folder should build protos before it runs any of the tests on travis.

This means that either some of the code hasn't been updated correctly, or the build instructions are wrong (which would need to be fixed for both the CI tests and the release builds)

**Comment by Alramech** [comment]
moved to #211

**Pull request closed without merging**
