### PR TITLE
[HIBIKE] Delete unused files

### PR DESCRIPTION
**Pull request by brandonxxlee**
Deleted unused files, Karthik approved files that can be deleted but someone should double check.

### CODE REVIEW

**Review by akumaraguru — CHANGES_REQUESTED** [review]
Looks good so far. There are some other files I think can go away as well.

reset.py - legacy code for a quirky bootloader when we made our own smartsensors. Currently this is redundantly called 3 times every time we run flash.sh. Make sure to remove the relevant lines from flash.sh as well.

hibike_architecture.pdf - how badly do we need this diagram? At the very least we should make something better designed, ideally as an svg

\_\_init\_\_.py - why does this import hibike_simulator.py? I don't see this anywhere in piecentral

**Comment by brandonxxlee** [comment]
I removed the hibike_architecture.pdf because its kinda jank, and its not even fully correct anymore. A new one should be made somehow at some point anyways that's up to date.

**Review by akumaraguru — APPROVED** [review]

**Comment by akumaraguru** [comment]
Could clean out reset.py as well, but I won't nitpick

**Comment by brandonxxlee** [comment]
I would, but I don't really want to touch something that I don't know at all, just in case. I'll merge this for now, and make an issue for that.

**Pull request merged**
